export const englishToArabicLetters = new Map([
    ["alif", "أ"],
    ["baa", "ب"],
    ["jeem", "ج"],
    ["daal", "د"],
    ["raa", "ر"],
    ["seen", "س"],
    ["saad", "ص"],
    ["Taa", "ط"],
    ["ain", "ع"],
    ["faa", "ف"],
    ["qaaf", "ق"],
    ["laam", "ل"],
    ["meem", "م"],
    ["noon", "ن"],
    ["haa", "هـ"],
    ["waw", "و"],
    ["yaa", "ي"],
]);
export const englishToArabicNumbers = new Map([
    ["1", "١"],
    ["2", "٢"],
    ["3", "٣"],
    ["4", "٤"],
    ["5", "٥"],
    ["6", "٦"],
    ["7", "٧"],
    ["8", "٨"],
    ["9", "٩"],
]);
